# Generated by Django 5.0.1 on 2024-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0002_remove_borrow_loan_date_borrow_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="return_date",
            field=models.DateField(null=True),
        ),
    ]
